-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


DROP TABLE IF EXISTS public.article;

CREATE TABLE IF NOT EXISTS public.article
(
    id integer NOT NULL DEFAULT nextval('users_id_seq'::regclass),
    user_id integer NOT NULL,
    titre character varying COLLATE pg_catalog."default" NOT NULL,
    article character varying COLLATE pg_catalog."default" NOT NULL,
    archiver boolean NOT NULL DEFAULT false,
    user_id_comm integer,
    date timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT article_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.commentaire;

CREATE TABLE IF NOT EXISTS public.commentaire
(
    id_commentaire integer NOT NULL DEFAULT nextval('users_id_seq'::regclass),
    user_id integer,
    date timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    text_commentaire character varying COLLATE pg_catalog."default" NOT NULL,
    user_id_article integer,
    CONSTRAINT commentaire_pkey PRIMARY KEY (id_commentaire)
);

DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL DEFAULT nextval('users_id_seq'::regclass),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    password character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.article
    ADD CONSTRAINT article_user_id_comm_fkey FOREIGN KEY (user_id_comm)
    REFERENCES public.commentaire (id_commentaire) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.article
    ADD CONSTRAINT article_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

